language: java
sudo: false

script: mvn clean assembly:assembly && zip -r apidocs target/apidocs

cache:
  directories:
    - .autoconf
    - $HOME/.m2

deploy:
  provider: releases
  on:
    tags: true
  skip_cleanup: true
  file:
    - target/jsontools-jar-with-dependencies.jar 
    - apidocs.zip
  api_key:
    secure: $GH_SECRET
